#!/usr/bin/env bash

set -euo pipefail

now () {
    date +%s.%N
}

export TARGET="$WD/bin/main"
export FLAGS=(
    -fdelete-null-pointer-checks
    -fshort-enums
    -O3
    "-std=gnu99"
    -Wall
    -Wbad-function-cast
    -Wcast-align
    "-Wcast-align=strict"
    -Wcast-qual
    -Wconversion
    -Wdate-time
    -Wdouble-promotion
    -Wduplicated-branches
    -Wduplicated-cond
    -Werror
    -Wextra
    -Wfatal-errors
    -Wfloat-equal
    "-Wformat=2"
    -Wformat-signedness
    -Winline
    -Wlogical-op
    -Wmissing-declarations
    -Wmissing-include-dirs
    -Wmissing-prototypes
    -Wnested-externs
    -Wnull-dereference
    -Wpacked
    -Wpedantic
    -Wpointer-arith
    -Wredundant-decls
    -Wshadow
    -Wstack-protector
    -Wstrict-prototypes
    -Wswitch-enum
    -Wtrampolines
    -Wundef
    -Wunused
    -Wunused-macros
    -Wwrite-strings
)

build_all () {
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build" || exit 1
    (
        set -x
        gcc \
            -lm \
            "${FLAGS[@]}" \
            primes.c \
            hash_table.c \
            main.c \
            -o "$TARGET"
    )
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
    build_all
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)

"$TARGET"
