#!/usr/bin/env bash

set -euo pipefail

export TARGET="$WD/bin/main"

now () {
    date +%s.%N
}

export FLAGS=(
    -Wall \
    -Wbad-function-cast \
    -Wcast-align \
    "-Wcast-align=strict" \
    -Wcast-qual \
    -Wconversion \
    -Wdate-time \
    -Wdouble-promotion \
    -Wduplicated-branches \
    -Wduplicated-cond \
    -Werror \
    -Wextra \
    -Wfatal-errors \
    -Wfloat-equal \
    -Wformat-signedness \
    "-Wformat=2" \
    -Winline \
    -Wlogical-op \
    -Wmissing-declarations \
    -Wmissing-include-dirs \
    -Wmissing-prototypes \
    -Wnested-externs \
    -Wnull-dereference \
    -Wpacked \
    -Wpadded \
    -Wpedantic \
    -Wpointer-arith \
    -Wredundant-decls \
    -Wshadow \
    -Wstack-protector \
    -Wstrict-prototypes \
    -Wswitch-default \
    -Wswitch-enum \
    -Wtrampolines \
    -Wundef \
    -Wunused \
    -Wunused-macros \
    -Wwrite-strings \
    -fdelete-null-pointer-checks
)

build_all () {
    cp "$WD/src"/* "$WD/build"
    cd "$WD/build" || exit 1
    gcc \
        -std=gnu99 \
        -O1 \
        -lm \
        "${FLAGS[@]}" \
        primes.c \
        hash_table.c \
        main.c \
        -o "$TARGET"
}

(
    start=$(now)
    clang-format -i -verbose "$WD/src"/* 2>&1 | sed 's/\/.*\///g'
    build_all
    end=$(now)
    python3 -c "print(\"Compiled! ({:.3f}s)\n\".format(${end} - ${start}))"
)

"$TARGET"
